package com.bll.lnkteacher.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bll.lnkteacher.mvp.model.AppBean;
import com.bll.lnkteacher.mvp.model.Book;
import com.bll.lnkteacher.mvp.model.CourseBean;
import com.bll.lnkteacher.mvp.model.DateEvent;
import com.bll.lnkteacher.mvp.model.DiaryBean;
import com.bll.lnkteacher.mvp.model.FreeNoteBean;
import com.bll.lnkteacher.mvp.model.ItemTypeBean;
import com.bll.lnkteacher.mvp.model.Note;
import com.bll.lnkteacher.mvp.model.NoteContent;
import com.bll.lnkteacher.mvp.model.RecordBean;
import com.bll.lnkteacher.mvp.model.WallpaperBean;

import com.bll.lnkteacher.greendao.AppBeanDao;
import com.bll.lnkteacher.greendao.BookDao;
import com.bll.lnkteacher.greendao.CourseBeanDao;
import com.bll.lnkteacher.greendao.DateEventDao;
import com.bll.lnkteacher.greendao.DiaryBeanDao;
import com.bll.lnkteacher.greendao.FreeNoteBeanDao;
import com.bll.lnkteacher.greendao.ItemTypeBeanDao;
import com.bll.lnkteacher.greendao.NoteDao;
import com.bll.lnkteacher.greendao.NoteContentDao;
import com.bll.lnkteacher.greendao.RecordBeanDao;
import com.bll.lnkteacher.greendao.WallpaperBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appBeanDaoConfig;
    private final DaoConfig bookDaoConfig;
    private final DaoConfig courseBeanDaoConfig;
    private final DaoConfig dateEventDaoConfig;
    private final DaoConfig diaryBeanDaoConfig;
    private final DaoConfig freeNoteBeanDaoConfig;
    private final DaoConfig itemTypeBeanDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig noteContentDaoConfig;
    private final DaoConfig recordBeanDaoConfig;
    private final DaoConfig wallpaperBeanDaoConfig;

    private final AppBeanDao appBeanDao;
    private final BookDao bookDao;
    private final CourseBeanDao courseBeanDao;
    private final DateEventDao dateEventDao;
    private final DiaryBeanDao diaryBeanDao;
    private final FreeNoteBeanDao freeNoteBeanDao;
    private final ItemTypeBeanDao itemTypeBeanDao;
    private final NoteDao noteDao;
    private final NoteContentDao noteContentDao;
    private final RecordBeanDao recordBeanDao;
    private final WallpaperBeanDao wallpaperBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appBeanDaoConfig = daoConfigMap.get(AppBeanDao.class).clone();
        appBeanDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        courseBeanDaoConfig = daoConfigMap.get(CourseBeanDao.class).clone();
        courseBeanDaoConfig.initIdentityScope(type);

        dateEventDaoConfig = daoConfigMap.get(DateEventDao.class).clone();
        dateEventDaoConfig.initIdentityScope(type);

        diaryBeanDaoConfig = daoConfigMap.get(DiaryBeanDao.class).clone();
        diaryBeanDaoConfig.initIdentityScope(type);

        freeNoteBeanDaoConfig = daoConfigMap.get(FreeNoteBeanDao.class).clone();
        freeNoteBeanDaoConfig.initIdentityScope(type);

        itemTypeBeanDaoConfig = daoConfigMap.get(ItemTypeBeanDao.class).clone();
        itemTypeBeanDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        noteContentDaoConfig = daoConfigMap.get(NoteContentDao.class).clone();
        noteContentDaoConfig.initIdentityScope(type);

        recordBeanDaoConfig = daoConfigMap.get(RecordBeanDao.class).clone();
        recordBeanDaoConfig.initIdentityScope(type);

        wallpaperBeanDaoConfig = daoConfigMap.get(WallpaperBeanDao.class).clone();
        wallpaperBeanDaoConfig.initIdentityScope(type);

        appBeanDao = new AppBeanDao(appBeanDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);
        courseBeanDao = new CourseBeanDao(courseBeanDaoConfig, this);
        dateEventDao = new DateEventDao(dateEventDaoConfig, this);
        diaryBeanDao = new DiaryBeanDao(diaryBeanDaoConfig, this);
        freeNoteBeanDao = new FreeNoteBeanDao(freeNoteBeanDaoConfig, this);
        itemTypeBeanDao = new ItemTypeBeanDao(itemTypeBeanDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        noteContentDao = new NoteContentDao(noteContentDaoConfig, this);
        recordBeanDao = new RecordBeanDao(recordBeanDaoConfig, this);
        wallpaperBeanDao = new WallpaperBeanDao(wallpaperBeanDaoConfig, this);

        registerDao(AppBean.class, appBeanDao);
        registerDao(Book.class, bookDao);
        registerDao(CourseBean.class, courseBeanDao);
        registerDao(DateEvent.class, dateEventDao);
        registerDao(DiaryBean.class, diaryBeanDao);
        registerDao(FreeNoteBean.class, freeNoteBeanDao);
        registerDao(ItemTypeBean.class, itemTypeBeanDao);
        registerDao(Note.class, noteDao);
        registerDao(NoteContent.class, noteContentDao);
        registerDao(RecordBean.class, recordBeanDao);
        registerDao(WallpaperBean.class, wallpaperBeanDao);
    }
    
    public void clear() {
        appBeanDaoConfig.clearIdentityScope();
        bookDaoConfig.clearIdentityScope();
        courseBeanDaoConfig.clearIdentityScope();
        dateEventDaoConfig.clearIdentityScope();
        diaryBeanDaoConfig.clearIdentityScope();
        freeNoteBeanDaoConfig.clearIdentityScope();
        itemTypeBeanDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        noteContentDaoConfig.clearIdentityScope();
        recordBeanDaoConfig.clearIdentityScope();
        wallpaperBeanDaoConfig.clearIdentityScope();
    }

    public AppBeanDao getAppBeanDao() {
        return appBeanDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public CourseBeanDao getCourseBeanDao() {
        return courseBeanDao;
    }

    public DateEventDao getDateEventDao() {
        return dateEventDao;
    }

    public DiaryBeanDao getDiaryBeanDao() {
        return diaryBeanDao;
    }

    public FreeNoteBeanDao getFreeNoteBeanDao() {
        return freeNoteBeanDao;
    }

    public ItemTypeBeanDao getItemTypeBeanDao() {
        return itemTypeBeanDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public NoteContentDao getNoteContentDao() {
        return noteContentDao;
    }

    public RecordBeanDao getRecordBeanDao() {
        return recordBeanDao;
    }

    public WallpaperBeanDao getWallpaperBeanDao() {
        return wallpaperBeanDao;
    }

}
