package com.bll.lnkteacher.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bll.lnkteacher.mvp.model.Book;
import com.bll.lnkteacher.mvp.model.BookTypeBean;
import com.bll.lnkteacher.mvp.model.CourseBean;
import com.bll.lnkteacher.mvp.model.DateEvent;
import com.bll.lnkteacher.mvp.model.Note;
import com.bll.lnkteacher.mvp.model.NoteContent;
import com.bll.lnkteacher.mvp.model.Notebook;

import com.bll.lnkteacher.greendao.BookDao;
import com.bll.lnkteacher.greendao.BookTypeBeanDao;
import com.bll.lnkteacher.greendao.CourseBeanDao;
import com.bll.lnkteacher.greendao.DateEventDao;
import com.bll.lnkteacher.greendao.NoteDao;
import com.bll.lnkteacher.greendao.NoteContentDao;
import com.bll.lnkteacher.greendao.NotebookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig bookTypeBeanDaoConfig;
    private final DaoConfig courseBeanDaoConfig;
    private final DaoConfig dateEventDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig noteContentDaoConfig;
    private final DaoConfig notebookDaoConfig;

    private final BookDao bookDao;
    private final BookTypeBeanDao bookTypeBeanDao;
    private final CourseBeanDao courseBeanDao;
    private final DateEventDao dateEventDao;
    private final NoteDao noteDao;
    private final NoteContentDao noteContentDao;
    private final NotebookDao notebookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        bookTypeBeanDaoConfig = daoConfigMap.get(BookTypeBeanDao.class).clone();
        bookTypeBeanDaoConfig.initIdentityScope(type);

        courseBeanDaoConfig = daoConfigMap.get(CourseBeanDao.class).clone();
        courseBeanDaoConfig.initIdentityScope(type);

        dateEventDaoConfig = daoConfigMap.get(DateEventDao.class).clone();
        dateEventDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        noteContentDaoConfig = daoConfigMap.get(NoteContentDao.class).clone();
        noteContentDaoConfig.initIdentityScope(type);

        notebookDaoConfig = daoConfigMap.get(NotebookDao.class).clone();
        notebookDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        bookTypeBeanDao = new BookTypeBeanDao(bookTypeBeanDaoConfig, this);
        courseBeanDao = new CourseBeanDao(courseBeanDaoConfig, this);
        dateEventDao = new DateEventDao(dateEventDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        noteContentDao = new NoteContentDao(noteContentDaoConfig, this);
        notebookDao = new NotebookDao(notebookDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(BookTypeBean.class, bookTypeBeanDao);
        registerDao(CourseBean.class, courseBeanDao);
        registerDao(DateEvent.class, dateEventDao);
        registerDao(Note.class, noteDao);
        registerDao(NoteContent.class, noteContentDao);
        registerDao(Notebook.class, notebookDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        bookTypeBeanDaoConfig.clearIdentityScope();
        courseBeanDaoConfig.clearIdentityScope();
        dateEventDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        noteContentDaoConfig.clearIdentityScope();
        notebookDaoConfig.clearIdentityScope();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public BookTypeBeanDao getBookTypeBeanDao() {
        return bookTypeBeanDao;
    }

    public CourseBeanDao getCourseBeanDao() {
        return courseBeanDao;
    }

    public DateEventDao getDateEventDao() {
        return dateEventDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public NoteContentDao getNoteContentDao() {
        return noteContentDao;
    }

    public NotebookDao getNotebookDao() {
        return notebookDao;
    }

}
