package com.bll.lnkteacher.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkteacher.mvp.model.HandoutBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HANDOUT_BEAN".
*/
public class HandoutBeanDao extends AbstractDao<HandoutBean, Long> {

    public static final String TABLENAME = "HANDOUT_BEAN";

    /**
     * Properties of entity HandoutBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property ImageUrl = new Property(3, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property BodyUrl = new Property(4, String.class, "bodyUrl", false, "BODY_URL");
        public final static Property TypeStr = new Property(5, String.class, "typeStr", false, "TYPE_STR");
        public final static Property BookPath = new Property(6, String.class, "bookPath", false, "BOOK_PATH");
        public final static Property BookDrawPath = new Property(7, String.class, "bookDrawPath", false, "BOOK_DRAW_PATH");
        public final static Property Date = new Property(8, long.class, "date", false, "DATE");
    }


    public HandoutBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HandoutBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HANDOUT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TITLE\" TEXT," + // 2: title
                "\"IMAGE_URL\" TEXT," + // 3: imageUrl
                "\"BODY_URL\" TEXT," + // 4: bodyUrl
                "\"TYPE_STR\" TEXT," + // 5: typeStr
                "\"BOOK_PATH\" TEXT," + // 6: bookPath
                "\"BOOK_DRAW_PATH\" TEXT," + // 7: bookDrawPath
                "\"DATE\" INTEGER NOT NULL );"); // 8: date
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HANDOUT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HandoutBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(4, imageUrl);
        }
 
        String bodyUrl = entity.getBodyUrl();
        if (bodyUrl != null) {
            stmt.bindString(5, bodyUrl);
        }
 
        String typeStr = entity.getTypeStr();
        if (typeStr != null) {
            stmt.bindString(6, typeStr);
        }
 
        String bookPath = entity.getBookPath();
        if (bookPath != null) {
            stmt.bindString(7, bookPath);
        }
 
        String bookDrawPath = entity.getBookDrawPath();
        if (bookDrawPath != null) {
            stmt.bindString(8, bookDrawPath);
        }
        stmt.bindLong(9, entity.getDate());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HandoutBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(4, imageUrl);
        }
 
        String bodyUrl = entity.getBodyUrl();
        if (bodyUrl != null) {
            stmt.bindString(5, bodyUrl);
        }
 
        String typeStr = entity.getTypeStr();
        if (typeStr != null) {
            stmt.bindString(6, typeStr);
        }
 
        String bookPath = entity.getBookPath();
        if (bookPath != null) {
            stmt.bindString(7, bookPath);
        }
 
        String bookDrawPath = entity.getBookDrawPath();
        if (bookDrawPath != null) {
            stmt.bindString(8, bookDrawPath);
        }
        stmt.bindLong(9, entity.getDate());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HandoutBean readEntity(Cursor cursor, int offset) {
        HandoutBean entity = new HandoutBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // imageUrl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bodyUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // typeStr
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // bookPath
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // bookDrawPath
            cursor.getLong(offset + 8) // date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HandoutBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImageUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBodyUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTypeStr(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBookPath(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBookDrawPath(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDate(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HandoutBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HandoutBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HandoutBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
