package com.bll.lnkteacher.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkteacher.mvp.model.homework.HomeworkContentTypeBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOMEWORK_CONTENT_TYPE_BEAN".
*/
public class HomeworkContentTypeBeanDao extends AbstractDao<HomeworkContentTypeBean, Long> {

    public static final String TABLENAME = "HOMEWORK_CONTENT_TYPE_BEAN";

    /**
     * Properties of entity HomeworkContentTypeBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Date = new Property(3, long.class, "date", false, "DATE");
        public final static Property Path = new Property(4, String.class, "path", false, "PATH");
        public final static Property TypeId = new Property(5, int.class, "typeId", false, "TYPE_ID");
        public final static Property ContentId = new Property(6, int.class, "contentId", false, "CONTENT_ID");
        public final static Property IsSave = new Property(7, Boolean.class, "isSave", false, "IS_SAVE");
    }


    public HomeworkContentTypeBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HomeworkContentTypeBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOMEWORK_CONTENT_TYPE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TITLE\" TEXT," + // 2: title
                "\"DATE\" INTEGER NOT NULL ," + // 3: date
                "\"PATH\" TEXT," + // 4: path
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 5: typeId
                "\"CONTENT_ID\" INTEGER NOT NULL ," + // 6: contentId
                "\"IS_SAVE\" INTEGER);"); // 7: isSave
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOMEWORK_CONTENT_TYPE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeworkContentTypeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getDate());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(5, path);
        }
        stmt.bindLong(6, entity.getTypeId());
        stmt.bindLong(7, entity.getContentId());
 
        Boolean isSave = entity.getIsSave();
        if (isSave != null) {
            stmt.bindLong(8, isSave ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeworkContentTypeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getDate());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(5, path);
        }
        stmt.bindLong(6, entity.getTypeId());
        stmt.bindLong(7, entity.getContentId());
 
        Boolean isSave = entity.getIsSave();
        if (isSave != null) {
            stmt.bindLong(8, isSave ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeworkContentTypeBean readEntity(Cursor cursor, int offset) {
        HomeworkContentTypeBean entity = new HomeworkContentTypeBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.getLong(offset + 3), // date
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // path
            cursor.getInt(offset + 5), // typeId
            cursor.getInt(offset + 6), // contentId
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0 // isSave
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeworkContentTypeBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.getLong(offset + 3));
        entity.setPath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTypeId(cursor.getInt(offset + 5));
        entity.setContentId(cursor.getInt(offset + 6));
        entity.setIsSave(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeworkContentTypeBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeworkContentTypeBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeworkContentTypeBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
