package com.bll.lnkteacher.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkteacher.mvp.model.homework.HomeworkContentBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOMEWORK_CONTENT_BEAN".
*/
public class HomeworkContentBeanDao extends AbstractDao<HomeworkContentBean, Long> {

    public static final String TABLENAME = "HOMEWORK_CONTENT_BEAN";

    /**
     * Properties of entity HomeworkContentBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property Date = new Property(2, long.class, "date", false, "DATE");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property TypeId = new Property(4, int.class, "typeId", false, "TYPE_ID");
        public final static Property ContentId = new Property(5, int.class, "contentId", false, "CONTENT_ID");
        public final static Property FilePath = new Property(6, String.class, "filePath", false, "FILE_PATH");
        public final static Property MergePath = new Property(7, String.class, "mergePath", false, "MERGE_PATH");
    }


    public HomeworkContentBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HomeworkContentBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOMEWORK_CONTENT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"DATE\" INTEGER NOT NULL ," + // 2: date
                "\"TITLE\" TEXT," + // 3: title
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 4: typeId
                "\"CONTENT_ID\" INTEGER NOT NULL ," + // 5: contentId
                "\"FILE_PATH\" TEXT," + // 6: filePath
                "\"MERGE_PATH\" TEXT);"); // 7: mergePath
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOMEWORK_CONTENT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeworkContentBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getDate());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
        stmt.bindLong(5, entity.getTypeId());
        stmt.bindLong(6, entity.getContentId());
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(7, filePath);
        }
 
        String mergePath = entity.getMergePath();
        if (mergePath != null) {
            stmt.bindString(8, mergePath);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeworkContentBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getDate());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
        stmt.bindLong(5, entity.getTypeId());
        stmt.bindLong(6, entity.getContentId());
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(7, filePath);
        }
 
        String mergePath = entity.getMergePath();
        if (mergePath != null) {
            stmt.bindString(8, mergePath);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeworkContentBean readEntity(Cursor cursor, int offset) {
        HomeworkContentBean entity = new HomeworkContentBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getLong(offset + 2), // date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.getInt(offset + 4), // typeId
            cursor.getInt(offset + 5), // contentId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // filePath
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // mergePath
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeworkContentBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setDate(cursor.getLong(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTypeId(cursor.getInt(offset + 4));
        entity.setContentId(cursor.getInt(offset + 5));
        entity.setFilePath(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMergePath(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeworkContentBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeworkContentBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeworkContentBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
