package com.bll.lnkteacher.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bll.lnkteacher.mvp.model.NoteContent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTE_CONTENT".
*/
public class NoteContentDao extends AbstractDao<NoteContent, Long> {

    public static final String TABLENAME = "NOTE_CONTENT";

    /**
     * Properties of entity NoteContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property TypeStr = new Property(2, String.class, "typeStr", false, "TYPE_STR");
        public final static Property NoteId = new Property(3, long.class, "noteId", false, "NOTE_ID");
        public final static Property Date = new Property(4, long.class, "date", false, "DATE");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
        public final static Property ResId = new Property(6, String.class, "resId", false, "RES_ID");
        public final static Property FilePath = new Property(7, String.class, "filePath", false, "FILE_PATH");
        public final static Property PathName = new Property(8, String.class, "pathName", false, "PATH_NAME");
        public final static Property Page = new Property(9, int.class, "page", false, "PAGE");
    }


    public NoteContentDao(DaoConfig config) {
        super(config);
    }
    
    public NoteContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTE_CONTENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TYPE_STR\" TEXT," + // 2: typeStr
                "\"NOTE_ID\" INTEGER NOT NULL ," + // 3: noteId
                "\"DATE\" INTEGER NOT NULL ," + // 4: date
                "\"TITLE\" TEXT," + // 5: title
                "\"RES_ID\" TEXT," + // 6: resId
                "\"FILE_PATH\" TEXT," + // 7: filePath
                "\"PATH_NAME\" TEXT," + // 8: pathName
                "\"PAGE\" INTEGER NOT NULL );"); // 9: page
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTE_CONTENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NoteContent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String typeStr = entity.getTypeStr();
        if (typeStr != null) {
            stmt.bindString(3, typeStr);
        }
        stmt.bindLong(4, entity.getNoteId());
        stmt.bindLong(5, entity.getDate());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String resId = entity.getResId();
        if (resId != null) {
            stmt.bindString(7, resId);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(8, filePath);
        }
 
        String pathName = entity.getPathName();
        if (pathName != null) {
            stmt.bindString(9, pathName);
        }
        stmt.bindLong(10, entity.getPage());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NoteContent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String typeStr = entity.getTypeStr();
        if (typeStr != null) {
            stmt.bindString(3, typeStr);
        }
        stmt.bindLong(4, entity.getNoteId());
        stmt.bindLong(5, entity.getDate());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String resId = entity.getResId();
        if (resId != null) {
            stmt.bindString(7, resId);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(8, filePath);
        }
 
        String pathName = entity.getPathName();
        if (pathName != null) {
            stmt.bindString(9, pathName);
        }
        stmt.bindLong(10, entity.getPage());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NoteContent readEntity(Cursor cursor, int offset) {
        NoteContent entity = new NoteContent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // typeStr
            cursor.getLong(offset + 3), // noteId
            cursor.getLong(offset + 4), // date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // title
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // resId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // filePath
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // pathName
            cursor.getInt(offset + 9) // page
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NoteContent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setTypeStr(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNoteId(cursor.getLong(offset + 3));
        entity.setDate(cursor.getLong(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setResId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFilePath(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPathName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPage(cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NoteContent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NoteContent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NoteContent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
